version: "4"
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=ttv_chatbot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"
  nextjs:
    build: .
    restart: always
    depends_on:
      - postgres
    ports:
      - "3000:3000"
